apiVersion: argoproj.io/v1alpha1 # Create a rollout resource
kind: Rollout
metadata:
  name: oes-visibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      #put values here

      component: visibility
  workloadRef: # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: oes-visibility
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: oes-visibility-stable
      previewService: oes-visibility-preview
      prePromotionAnalysis:
        templates:
          - templateName: oes-visibility
          - templateName: load-executor-jmeter-job
        args:
          - name: baseline-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: preview-hash
            valueFrom:
              podTemplateHashValue: Latest
          - name: servicename
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
